### ISSUE TITLE
[Feature Request]TomTom support

### ISSUE THREAD

**Issue by fubaBfA** [steventroughtonsmith/instanceportals#7]
Hi there,
is it possible to add TomTom support to your AddOn?
Means rightclick a Dungeon/Raid Icon to add a TomTom Waypoint Arrow to the Dungeon Entrance.

Would be very nice!

Thanks ;)

**Comment by steventroughtonsmith** [comment]
Keeping this around because it's something I'd like to do, but could be a big problem with the existing dungeon location database I've made — dungeon portal coords are all based on their map location for clarity, which sometimes is veeery different from their actual GPS coords (for example, Tempest Keep & its dungeons, because of how stylized it is on the map, is nowhere near accurate for GPS)
